name: Build and deploy to cloud run

on:
  push:
    branchs:
    -master

env:
  PROJECT_ID:${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: ml-api
  BASIC_AUTH_USERNAME: {{ secrets.BASIC_AUTH_PASSWORD }}
  BASIC_AUTH_PASSWORD: {{ secrets.BASIC_AUTH_USERNAME }}

jobs:
  setup-build-deploy:
    name: setup, build, and deploy
    run-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with: 
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
    
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --config cloudbuild.yaml \
          --substitutions _BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME, _BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD, _IMAGE_TAG=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GIT_HUB_SHA" \
          --plataform "managed" \
          --allow-unauthenticated \
          --port 5000
